// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYqAX7EJ_GNR-bKTw_PufUrgsgkLhML-Y',
    appId: '1:392252639155:web:822ad8d9ccafbd72e0adc6',
    messagingSenderId: '392252639155',
    projectId: 'avocat-recommendation',
    authDomain: 'avocat-recommendation.firebaseapp.com',
    storageBucket: 'avocat-recommendation.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Sf6QgqxXnU_cQJaIf87X_b3oALFixPk',
    appId: '1:392252639155:android:47d3d966eaa0fd5de0adc6',
    messagingSenderId: '392252639155',
    projectId: 'avocat-recommendation',
    storageBucket: 'avocat-recommendation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3UyLwdwA-gtw7BTobxtRGcI2tAT0RE6Y',
    appId: '1:392252639155:ios:4984a065bf52e213e0adc6',
    messagingSenderId: '392252639155',
    projectId: 'avocat-recommendation',
    storageBucket: 'avocat-recommendation.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3UyLwdwA-gtw7BTobxtRGcI2tAT0RE6Y',
    appId: '1:392252639155:ios:4984a065bf52e213e0adc6',
    messagingSenderId: '392252639155',
    projectId: 'avocat-recommendation',
    storageBucket: 'avocat-recommendation.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYqAX7EJ_GNR-bKTw_PufUrgsgkLhML-Y',
    appId: '1:392252639155:web:5545a799e67d7cb8e0adc6',
    messagingSenderId: '392252639155',
    projectId: 'avocat-recommendation',
    authDomain: 'avocat-recommendation.firebaseapp.com',
    storageBucket: 'avocat-recommendation.firebasestorage.app',
  );
}
